-- ایجاد جدول brands (فقط اگر وجود نداشته باشد)
CREATE TABLE IF NOT EXISTS brands (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT,
  image TEXT
);

-- ایجاد جدول categories (فقط اگر وجود نداشته باشد)
CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT
);

-- ایجاد جدول products (فقط اگر وجود نداشته باشد)

-- ایجاد جدول profiles (شناسه برابر با auth.user_id)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  phone text,
  created_at timestamp with time zone default now()
);

-- ایجاد جدول orders
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  total_amount bigint not null default 0,
  payment_status text not null default 'pending',
  full_name text not null,
  address text not null,
  postal_code text not null,
  phone text not null,
  created_at timestamp with time zone default now()
);

-- ایجاد جدول order_items
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint,
  name_snapshot text not null,
  unit_price bigint not null,
  quantity int not null default 1
);

-- RLS
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- سیاست‌ها
do $$ begin
  create policy if not exists "profiles_self" on public.profiles
    for select using (auth.uid() = id)
    with check (auth.uid() = id);
exception when others then null; end $$;

do $$ begin
  create policy if not exists "orders_owner" on public.orders
    for select using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when others then null; end $$;

do $$ begin
  create policy if not exists "order_items_by_owner" on public.order_items
    for select using (exists (
      select 1 from public.orders o where o.id = order_items.order_id and o.user_id = auth.uid()
    ));
exception when others then null; end $$;

-- ایندکس‌ها
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);

-- نکته: تنظیمات سرویس SMS و شماره ارسال در Supabase Auth باید در داشبورد انجام شود.
CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price VARCHAR(50) NOT NULL,
  originalPrice VARCHAR(50),
  brand VARCHAR(100) NOT NULL,
  padBrand VARCHAR(100),
  vehicleType VARCHAR(50),
  category VARCHAR(100) NOT NULL,
  suitableFor TEXT,
  stockStatus VARCHAR(50) DEFAULT 'موجود',
  stockCount INTEGER DEFAULT 0,
  description TEXT,
  image TEXT,
  specifications JSONB,
  features TEXT[],
  reviews JSONB,
  badges JSONB DEFAULT '{"discount": false, "bestseller": false, "new": false}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ایجاد جدول pad_brands (فقط اگر وجود نداشته باشد)
CREATE TABLE IF NOT EXISTS pad_brands (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT
);

-- فعال کردن RLS (فقط اگر فعال نباشد)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public'
    AND tablename = 'brands'
    AND rowsecurity = true
  ) THEN
    ALTER TABLE brands ENABLE ROW LEVEL SECURITY;
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public'
    AND tablename = 'categories'
    AND rowsecurity = true
  ) THEN
    ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public'
    AND tablename = 'products'
    AND rowsecurity = true
  ) THEN
    ALTER TABLE products ENABLE ROW LEVEL SECURITY;
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public'
    AND tablename = 'pad_brands'
    AND rowsecurity = true
  ) THEN
    ALTER TABLE pad_brands ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;

-- ایجاد policy برای خواندن (همه کاربران) - فقط اگر وجود نداشته باشد
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'brands'
    AND policyname = 'Allow public read access to brands'
  ) THEN
    CREATE POLICY "Allow public read access to brands" ON brands
      FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'categories'
    AND policyname = 'Allow public read access to categories'
  ) THEN
    CREATE POLICY "Allow public read access to categories" ON categories
      FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'products'
    AND policyname = 'Allow public read access to products'
  ) THEN
    CREATE POLICY "Allow public read access to products" ON products
      FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'pad_brands'
    AND policyname = 'Allow public read access to pad_brands'
  ) THEN
    CREATE POLICY "Allow public read access to pad_brands" ON pad_brands
      FOR SELECT USING (true);
  END IF;
END $$;

-- ایجاد policy برای نوشتن (فقط ادمین) - فقط اگر وجود نداشته باشد
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'brands'
    AND policyname = 'Allow admin insert/update/delete on brands'
  ) THEN
    CREATE POLICY "Allow admin insert/update/delete on brands" ON brands
      FOR ALL USING (true);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'categories'
    AND policyname = 'Allow admin insert/update/delete on categories'
  ) THEN
    CREATE POLICY "Allow admin insert/update/delete on categories" ON categories
      FOR ALL USING (true);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'products'
    AND policyname = 'Allow admin insert/update/delete on products'
  ) THEN
    CREATE POLICY "Allow admin insert/update/delete on products" ON products
      FOR ALL USING (true);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename = 'pad_brands'
    AND policyname = 'Allow admin insert/update/delete on pad_brands'
  ) THEN
    CREATE POLICY "Allow admin insert/update/delete on pad_brands" ON pad_brands
      FOR ALL USING (true);
  END IF;
END $$;

-- اضافه کردن برندهای پیش‌فرض (فقط اگر وجود نداشته باشند)
INSERT INTO brands (name, description)
SELECT v.name, v.description
FROM (VALUES
  ('تویوتا','برند تویوتا'),
  ('هیوندای','برند هیوندای'),
  ('نیسان','برند نیسان'),
  ('کیا','برند کیا'),
  ('لکسوس','برند لکسوس'),
  ('جیلی','برند جیلی'),
  ('مزدا','برند مزدا'),
  ('ام‌جی','برند ام‌جی'),
  ('میتسوبیشی','برند میتسوبیشی'),
  ('فولکس‌واگن','برند فولکس‌واگن'),
  ('سایپا','برند سایپا'),
  ('سوزوکی','برند سوزوکی'),
  ('رنو','برند رنو'),
  ('پژو','برند پژو'),
  ('ایران‌خودرو','برند ایران‌خودرو'),
  ('فاو','برند فاو'),
  ('جی‌ای‌سی','برند جی‌ای‌سی')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM brands b WHERE b.name = v.name);

-- اضافه کردن دسته‌بندی‌های پیش‌فرض (فقط اگر وجود نداشته باشند)
INSERT INTO categories (name, description)
SELECT v.name, v.description
FROM (VALUES
  ('دیسکی','دسته‌بندی دیسکی'),
  ('کمپوزیتی','دسته‌بندی کمپوزیتی'),
  ('سرامیکی','دسته‌بندی سرامیکی'),
  ('فلزی','دسته‌بندی فلزی'),
  ('پلاستیکی','دسته‌بندی پلاستیکی')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.name = v.name);

-- اطمینان از وجود ستون padBrand در جدول products
ALTER TABLE IF EXISTS products
  ADD COLUMN IF NOT EXISTS padBrand VARCHAR(100);

-- اطمینان از وجود ستون vehicleType در جدول products
ALTER TABLE IF EXISTS products
  ADD COLUMN IF NOT EXISTS vehicleType VARCHAR(50);

-- اطمینان از وجود ستون badges در جدول products
ALTER TABLE IF EXISTS products
  ADD COLUMN IF NOT EXISTS badges JSONB DEFAULT '{"discount": false, "bestseller": false, "new": false}';

-- اضافه کردن برندهای لنت پیش‌فرض (فقط اگر وجود نداشته باشند)
INSERT INTO pad_brands (name, description)
SELECT v.name, v.description
FROM (VALUES
  ('آفورتیس','برند لنت آفورتیس'),
  ('آسیمکو','برند لنت آسیمکو'),
  ('امکو','برند لنت امکو')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM pad_brands p WHERE p.name = v.name);

-- ایجاد Storage Bucket برای عکس‌های محصولات
-- این دستورات باید در SQL Editor اجرا شوند

-- ایجاد bucket (اگر وجود نداشته باشد)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO NOTHING;

-- ایجاد policy برای خواندن عکس‌ها (همه کاربران)
-- CREATE POLICY "Allow public read access to product images" ON storage.objects FOR SELECT USING (bucket_id = 'product-images');

-- ایجاد policy برای آپلود عکس‌ها (فقط ادمین)
-- CREATE POLICY "Allow admin upload to product images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'product-images');

-- ایجاد policy برای حذف عکس‌ها (فقط ادمین)
-- CREATE POLICY "Allow admin delete from product images" ON storage.objects FOR DELETE USING (bucket_id = 'product-images');
